### ISSUE TITLE
Unauthenticated routes return status 500

### ISSUE THREAD

**Issue by davestewart** [pktharindu/laravel-api-boilerplate-passport#8]
Hello,

Great repo!

I'm coming back to Laravel after a few years and wanted something to throw an API up quick, and I'm hoping this is it!

Anyway, got it all up and running very easily, but hit the `api/users` route just to test and I get a status of 500.

Surely this should be 401?

**Comment by pktharindu** [comment]
Guess I forgot to mark this as solved 😅
